import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header className="p-5 text-center border-2 border-black rounded-lg mx-4 my-4">
          <p>Some temporary header with(out) some pretty background image...</p>
      </header>

      <main className="min-h-[60vh] p-5">
          {children}
      </main>

      <footer className="p-5 border-2 border-black rounded-lg mx-4 my-4">
          <div className="flex gap-10 mb-5 items-end">
              <div className="p-8 border-2 border-black rounded-lg">
                  <p>Istedgade 101, 1 sal.<br/>Copenhagen<br/>1650, Vesterbro</p>
                  <p>?contact info?</p>
              </div>
              <div className="p-5 border-2 border-black rounded-lg flex-1 flex items-center justify-center gap-4">
                  <a href="https://instagram.com/bebsisbadekar/" target="_blank" rel="noopener noreferrer">
                      <img src="/icons/instagram.svg" alt="Instagram" className="w-6 h-6" />
                  </a>
                  <a href="/terms">Terms and Conditions</a>
                  <span>-</span>
                  <a href="/privacy">Privacy Policy</a>
              </div>
          </div>
      </footer>
      </body>
      </html>
  );
}
